### ISSUE TITLE
Introduce upgrade handlers to utilize software upgrade governance proposals

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/classic#10]
**Problem definition**
We are currently not able to use upgrade handlers for "chain upgrades" due to issues with the version map. Fixing this will allow us to workaround the "genesis import issue" and adopt the upgrade strategy which seems to be preferred by the Cosmos developer community.

**Feature specification**
TODO - Spec

**Additional context**
TODO - Tasks

**Comment by inon-man** [comment]
I will look into this issue this week.

**Comment by nghuyenthevinh2000** [comment]
please read over this: https://github.com/classic-terra/classic/pull/28

I discuss why upgrade version map fails and hot fix for 1.0.4 upgrade handler
