### ISSUE TITLE
Fix Columbus-5 version map

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/classic#11]
**Problem definition**
Assess the state of our current “version map” and determine how it can be patched to reflect the current state of our system.

**Feature specification**

**Acceptance Criteria**
- Upgrade is applied and is running correctly.

**Additional context**
- [ ] Confirm upgrade map has been fixed.  Meet with @inon-man and confirm upgrade work completed will resolve issue. (Vinh)

**Comment by nghuyenthevinh2000** [comment]
here is version map comparison between juno (main) and terra classic (main)

<img width="1512" alt="Screenshot 2023-01-04 at 11 26 24" src="https://user-images.githubusercontent.com/23058164/210484550-8be5f6ac-ad6b-4270-8274-839f0e51040f.png">

**Comment by nghuyenthevinh2000** [comment]
please read over this: https://github.com/classic-terra/classic/pull/28

I discuss why upgrade version map fails and hot fix for 1.0.4 upgrade handler

**Comment by ZaradarBH** [comment]
@inon-man @nghuyenthevinh2000 has both confirmed it will work. We still have a pending test with the mainnet DB, but as such that will be uncovered when we begin regression testing for the 1.0.5 release :)
