### ISSUE TITLE
Test/Upgrade “estimate-fee” client logic (LCD) in auth module to ensure “burn tax” is calculated correctly

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/classic#14]
**Problem definition**
We found out that the LCD "estimate-fee" logic is calculated directly in the client which means we had to add in a "block height guard" to ensure that it added the "burn tax" correctly. The fix was done in October, but could do with some more testing.

**Feature specification**
- Add the "burn tax" to the "estimate-fee" query.

**Additional context**
- [x] Fix "estimate-fee" bug in [custom/auth/client/utils/feeutils.go](https://github.com/classic-terra/classic/commit/403cc129e42ab0dfef2eb39cac58ad8e40c6bec9#diff-779cf52996e34d2651a8eece34b51e5ecacff277661b73fda175eeebe2ebcf89)
- [x] Test software patch on full node mainnet
- [x] Test bug fix on testnet

**Comment by edk208** [comment]
confirmed working on full node on mainnet (columbus-5).  will test as validator on testnet next
