### ISSUE TITLE
Research strategies for optimizing Terra Classics "persistence layer"

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/classic#16]
**Problem definition**
Investigate PebbleDB for speed improvements (PCI 4.0/NVME) to the backend, discontinue support for goleveldb/rocksdb.
Investigate BadgerDb for dealing with "large KVstore blobs"

**Feature specification**
Provide benchmarking data for "terrad" using different KVStore configurations in order to gauge the different performance profiles when dealing with various types of data (lots of small values, lots of big blobs, mixed)

**Additional context**
- [x] Study LSM-based KVStore architectures (RocksDb/PebbleDb)
- [x] Study LSM-based w. seperate value log KVStore architectures (BadgerDb)
- [x] Speak with Aaron about the state of the Read/WriteSource implementations for the orm
- [x] Test case for user story: "Sequence of pre-orderered keys with 8B values"
- [x] Test case for user story: "Sequence of unordered keys with 8B values"
- [x] Test case for user story: "Sequence of pre-orderered keys with 8KB values"
- [x] Test case for user story: "Sequence of unordered keys with 8KB values"
- [x] Test case for user story: "Sequence of pre-orderered keys with 64KB values"
- [x] Test case for user story: "Sequence of unordered keys with 64KB values"
- [x] Test case for user story: "Sequence of pre-orderered keys with 4GB values"
- [x] Test case for user story: "Sequence of unordered keys with 4GB values"
- [x] Fix "unit test breakage" when running "go test --bench ."
- [x] Implement test scripts for benchmarking
- [x] Benchmark "KVStore" using RocksDB to establish baseline
- [x] Benchmark "KVStore" using PebbleDB for comparison
- [x] Benchmark "KVStore" using BadgerDB for comparison
- [x] Benchmark "KVStore" with  columbus-5 genesis using PebbleDB for comparison
- [x] Benchmark "KVStore" with  columbus-5 genesis using BadgerDB for comparison

***Links***
- LSM-tree research @ https://www.usenix.org/system/files/conference/fast16/fast16-papers-lu.pdf
- LSM-trees explained @ https://medium.com/swlh/log-structured-merge-trees-9c8e2bea89e8
- BadgerDB vs RocksDB @ https://dgraph.io/blog/post/badger-over-rocksdb-in-dgraph/
- GoLang profliing @ https://hackernoon.com/go-the-complete-guide-to-profiling-your-code-h51r3waz
- Test case @ https://github.com/classic-terra/documents/blob/main/test%20cases/performance-profiling-persistence-of-lsm-architectures.md

**Comment by ZaradarBH** [comment]
https://www.usenix.org/system/files/conference/fast16/fast16-papers-lu.pdf

**Comment by ZaradarBH** [comment]
https://medium.com/swlh/log-structured-merge-trees-9c8e2bea89e8

**Comment by ZaradarBH** [comment]
https://dgraph.io/blog/post/badger-over-rocksdb-in-dgraph/

**Comment by nghuyenthevinh2000** [comment]
I understand the following steps for this task:
1. we build or find a tool to generate: "types of data (lots of small values, lots of big blobs, mixed)"
2. feed those values directly into cosmos db
3. compare different db on how quick and how much load can handle
4. write documents as acceptable output for this task

Am I missing anything? or any few more suggestions? @ZaradarBH

**Comment by ZaradarBH** [comment]
I had a chat with OpenAI (ChatGPT) this morning on KV store architectures. Here is what it said:

**Question** 
`lsm kvstore architecture`

**Answer**
```
LSM (Log-Structured Merge) is a storage architecture used in databases and other systems to store large amounts of data. The LSM-KV store (Key-Value store) is a variation of LSM that is optimized for key-value data.
In an LSM-KV store, data is organized as a set of sorted tables (often called "levels") and a log-structured memory (LSM tree) that tracks recent writes. When a new key-value pair is added, it is first written to the log-structured memory. Periodically, the LSM tree is merged with one of the tables, creating a new, larger table. As the tables become larger, the number of merge operations needed to maintain them decreases, making the system more efficient.
LSM-KV stores are often used in databases and other systems that need to store large amounts of data, handle high write loads, and provide low-latency read operations. One of the popular Database using LSM is RocksDB. The systems are designed to be highly parallelizable and can take advantage of modern multi-core and many-core processors to achieve high performance.
In summary: LSM-KV is an optimized key-value storage architecture that uses log-structured memory and a set of sorted tables to store large amounts of data. This design is optimized for high write loads and low-latency read operations, and can be highly parallelized for performance.
```

**Question**
`wisckey performance`

**Answer**
```
WiscKey is a key-value store that combines the advantages of Log-Structured Merge (LSM) trees and Write-Optimized Memory-Bounded Log-Structured Merge (WOM-LSM) trees, two commonly used storage architectures for databases and other systems.
WiscKey was designed to improve performance in write-heavy workloads and mixed read-write workloads. It uses a combination of LSM and WOM-LSM trees to handle both read and write operations efficiently. The LSM tree is used for read operations and the WOM-LSM tree is used for write operations, and both are merged periodically to ensure consistency.
In benchmark test, WiscKey has shown to have a very good performance, with low latency and high throughput. In a test comparing WiscKey with RocksDB and LevelDB, a widely used open-source key-value stores, WiscKey achieved lower latencies and higher throughputs than RocksDB and LevelDB in read-write workloads. Also with WiscKey demonstrated lower latencies than other LSM-based store like RocksDB and LevelDB for range queries.
So, in summary, WiscKey was designed to improve performance in write-heavy and mixed read-write workloads by combining the advantages of LSM and WOM-LSM storage architectures. In benchmark test, WiscKey has demonstrated good performance, with lower latency and higher throughput than other popular LSM-based key-value stores.

```
**Question**
`badger db`

**Answer**
```
BadgerDB is a high-performance, key-value database that is written in the Go programming language. It is designed to be lightweight and fast, and is intended for use in systems that require low-latency, high-throughput data storage.
BadgerDB uses a modified version of the Log-Structured Merge (LSM) tree data structure to store its data. The LSM tree is a form of disk-based storage that is optimized for high write loads and can provide low-latency read operations. BadgerDB also implements a technique called value log compaction to reduce disk space usage.
One of the major advantages of BadgerDB is its high performance. It is designed to be very fast and can handle high write loads and read loads with low latencies. It is also designed to be concurrent and it allows multiple readers and writers to access the database simultaneously without blocking each other. Additionally, BadgerDB supports a memory-mapped mode, in which the database is stored in memory and accessed directly. This can provide very fast access to the data, at the cost of increased memory usage.
Another feature of BadgerDB is its support for data expiration, allowing data to be automatically deleted after a certain amount of time.
BadgerDB is also intended to be easy to use. It has a simple, high-level API for interacting with the database, and it provides a number of features that are not typically found in other key-value databases, such as support for prefix iteration and merge operations.
In summary, BadgerDB is a high-performance, key-value database written in Go. It uses a modified LSM tree data structure, value log compaction and memory-mapped mode to provide high write and read performance. It also provides easy to use API, data expiration feature and other additional functionalities.
```

**Comment by StrathCole** [comment]
You should ask it more natural questions 😉
That thing is really impressive, especially when referring to previous questions.

**Comment by ZaradarBH** [comment]
A friend of mine started  using it as a coding bot :P

**Comment by ZaradarBH** [comment]
https://hackernoon.com/go-the-complete-guide-to-profiling-your-code-h51r3waz - tips & tricks for profiling

**Comment by ZaradarBH** [comment]
https://github.com/classic-terra/documents/blob/main/test%20cases/performance-profiling-persistence-of-lsm-architectures.md

**Comment by nghuyenthevinh2000** [comment]
tool: https://github.com/nghuyenthevinh2000/db-benchmark

**Comment by ZaradarBH** [comment]
Initial findings are that BadgerDb seems to be an order of magnitude faster then its competition when dealing with writes (https://dgraph.io/blog/post/badger-lmdb-boltdb/) and more or less on parity with the others in most read scenarios (x1.5 -  x2 slower). There is is a range when dealing with objects larger then 80000B where it seems  to level out when dealing with a high number of sequential writes and in some cases Pebble is faster. However if one where to pick BadgerDb would probably provide the best overall performance boost compared to the current GoLevelDb LSM-tree implementation that is currently being used.

We will work to produce larger test data sets so we can compile some larger data sets for pprof to process so we can visualize the differences and certify the initial findings via "empirical evidence". Once we are satisfied with the benchmarking results we will produce a small report for people to digest.

**Comment by ZaradarBH** [comment]
It seems that BadgerDB also has support for StreamWriters with up to 1.6 Gbps thru-put by circumventing compactions entirely, which could explain the high write performance. There is a good article on it here: https://dgraph.io/blog/post/badger-v1.6.0-release/

Quote: "StreamWriter can write multiple streams, as long as each stream contains sorted keys and the streams are non-overlapping. The output from badger.Stream framework provides that guarantee. StreamWriter works by avoiding LSM tree compactions, instead building SSTables and arranging them directly in the many levels of the tree. This can write almost as fast as disk allows. Our [experiments](https://github.com/dgraph-io/badger/commit/1725096e24a2bbf932d14808e57d78d296753606) show writes at a rate of 200MBps, writing over 1 billion keys in around 3m20s." (edited)

**Comment by ZaradarBH** [comment]
Based on our review with @inon-man he has indicated that we need to do more testing of this via the actual genesis data as he is concerned about moving away from GoLevelDb once we start testing this on "real world" data. I think its a very valid concern and we will focus on testing this with PebbleDB and BadgerDB  which seem to be the last two remaining candidates in our benchmarking :)

**Comment by ZaradarBH** [comment]
PebbleDb crashes when dealing with a genesis over 4GB in size:

rm -rf testdb*
go run -ldflags '-X [github.com/cosmos/cosmos-sdk/types.DBBackend=pebbledb](http://github.com/cosmos/cosmos-sdk/types.DBBackend=pebbledb)' -tags 'pebbledb' data.go main.go
go: downloading [golang.org/x/exp](http://golang.org/x/exp) v0.0.0-20200513190911-00229845015e
go: downloading [github.com/kr/pretty](http://github.com/kr/pretty) v0.2.1
you are getting backend = pebbledb
loading genesis state
panic: pebble: batch too large: >= 4.0 G

**Comment by ZaradarBH** [comment]
BadgerDB chucks thru the genesis and completes loading:

rm -rf testdb*
go run -ldflags '-X github.com/cosmos/cosmos-sdk/types.DBBackend=badgerdb' -tags 'badgerdb' data.go main.go
go: downloading github.com/klauspost/compress v1.12.3
you are getting backend = badgerdb 
loading genesis state

**Comment by ZaradarBH** [comment]
I think we can conclude that BadgerDB is the best KVStore option for Terra Classic looking at the size of our genesis. It also seems to be the most performant of the options avilable in TM-DB so it might be worth suggesting to validators to switch to this storage.

**Comment by ZaradarBH** [comment]
https://github.com/cosmos/cosmos-sdk/discussions/9331#discussioncomment-738168
