### ISSUE TITLE
[Support] ZuluSpl0it CW20-Bonding Contract Testing

### ISSUE THREAD

**Issue by fragwuerdig** [classic-terra/classic#20]
**Describe the bug**

This issue has to be further investigated. A guy named LbunPyro deployed the following contract on TerraClassic:

https://github.com/ZuluSpl0it/contracts/blob/main/contracts/cw20-bonding/src/contract.rs

The instantiated contract is here:

https://finder.terra.money/classic/address/terra1r8t57xzx4ekwc6ts7nc8cg0gsg7jrpf9pwmnug

The issue is that contract execution for the ExecuteMessage {"buy":{}} fails every time  although there is enough fee coins in the ExecuteMsg and the gas limit is appropriate.

See for example failed tx hash: 

https://finder.classic-terra.com/classic/tx/853E6564C776C7946FC4D5BF160B3BE79F080E0D403A785BAAA889AE78F33B8C

**To Reproduce**

Given above contract address try to execute message {"buy": {}}

**Context & versions**

This issue does not apply for any other messages that are accepted by the contract. Also: It does not seem to apply to Bombay test network, which basically does not implement the tax. The buy message from the contract is the only message that stacks other send messages on top of the response stack.

My first guess is that there is an issue with the tax handling. This has to be further investigated.

@faddat : Do you have someone who I can talk to and who is an expert on contracts? Just so that I can exclude any issues with the contract itself ...

**Comment by StrathCole** [comment]
You need so subtract tax /fee amount from the amount to send in MsgSend.

**Comment by ZaradarBH** [comment]
Its most likely because the FeeUtil fix I did back in October has not made it into mainnet yet so the LCD doesnt include the burn  tax in the estimate-fee query

**Comment by ZaradarBH** [comment]
https://github.com/classic-terra/classic/issues/14

**Comment by StrathCole** [comment]
```fn compute_tax(querier: &QuerierWrapper, amount: Uint128, denom: String) -> StdResult<Uint128> {
    let terra_querier = TerraQuerier::new(querier);
    let tax_rate: Decimal = (terra_querier.query_tax_rate()?).rate;
    let tax_cap: Uint128 = (terra_querier.query_tax_cap(denom)?).cap;
    Ok(std::cmp::min(
        amount.checked_sub(amount.multiply_ratio(
            DECIMAL_FRACTION,
            (DECIMAL_FRACTION * tax_rate) + DECIMAL_FRACTION,
        ))?,
        tax_cap,
    ))
}

let tax_amount =
        compute_tax(&deps.querier, amount, "uluna".to_string())? + Uint128::new(1u128);
    if tax_amount > amount {
        return Err(ContractError::FundsTooSmall {});
    }

    let burn_msg = CosmosMsg::Bank(BankMsg::Send {
        to_address: cfg.burn_wallet.to_string(),
        amount: vec![Coin {
            denom: "uluna".to_string(),
            amount: amount - tax_amount,
        }],
    });
```

**Comment by StrathCole** [comment]
Sorry, only on mobile, so code is maybe not 100%

**Comment by fragwuerdig** [comment]
Ok. That's helpful. LbunPyro will try that solution. I'll let you know.

**Comment by ZuluSpl0it** [comment]
Let me see if I understand correctly from the code snippet above:

I just need push an additional msg onto the response that is specific to the burn tax (1.2%). So something like is:

If I send BOB 100000000 uluna, then I also need to send cfg.burn_wallet.to_string() 1200000 uluna. That 1200000 needs to be pushed on the response stack like:

    messages.push(CosmosMsg::Bank(BankMsg::Send {
        to_address: cfg.burn_wallet.to_string(),
        amount: vec![Coin {
            denom: "uluna".to_string(),
            amount: tax_amount,
        }],
    }));

So the LCD checks that the 1.2% is sent to the burn wallet. What is the correct burn wallet address? I want to make sure I am utilizing the correct one.

**Comment by ZuluSpl0it** [comment]
Didn't work for me. I instantiated a new contract: 
https://finder.terra.money/classic/address/terra1g7lrkuzrk4z6cjyklu4ezn7ya9753srdmtgs45

I specifically sent the 1.2% tax to the burn address (terra1sk06e3dyexuq4shw77y3dsv480xv42mq73anxu) along with my other MsgSends in one transaction. Still got the insufficient fee error.

**Comment by JoowonYun** [comment]
Doesn't the current structure automatically deduct taxes from the executing wallet?
Need to leave tax amount to the contract address, but it doesn't seem to be left with the current code.

**Comment by fragwuerdig** [comment]
Actually, the taxes are taken from the fee-Coins that are sent alongside the TX. You can look that up in the ante-handler of the auth module. But if you want to send a TX from inside a CosmWasm contract, then you don't have the possibility to attach fee coins to the message (look [here](https://docs.rs/cosmwasm-std/0.16.4/cosmwasm_std/enum.BankMsg.html) - you can only specify "denom" and "amount" to be sent). There are now two possibilities:

1.) The tax amount is taken from the original senders fee coins (thats what I believed initially)
2.) CosmWasm automagically appends the required fee coins to the message sent by a contract...

**Comment by JoowonYun** [comment]
> Actually, the taxes are taken from the fee-Coins that are sent alongside the TX. You can look that up in the ante-handler of the auth module. But if you want to send a TX from inside a CosmWasm contract, then you don't have the possibility to attach fee coins to the message (look [here](https://docs.rs/cosmwasm-std/0.16.4/cosmwasm_std/enum.BankMsg.html) - you can only specify "denom" and "amount" to be sent). There are now two possibilities:
> 
> 1.) The tax amount is taken from the original senders fee coins (thats what I believed initially) 2.) CosmWasm automagically appends the required fee coins to the message sent by a contract...

In the logic of the current contract, 2.) seems to be correct. I think that need to look at cosmwasm tax deduct a bit. 
If you remain enough coins to pay the tax at the contract address, they will be automatically deducted. Terraswap uses it that way.

**Comment by JoowonYun** [comment]
@fragwuerdig  Here is the contract address fee deduct for SubMsg is done through this code.
https://github.com/classic-terra/classic/blob/6b8b172615ecf51e3e1fced43284ae3b55d23a0c/x/wasm/keeper/connector.go#L136-L137

**Comment by ZuluSpl0it** [comment]
[fragwuerdig](https://github.com/fragwuerdig) informed me that I don't need to actually send to the burn address from my smart contract. Just that the smart contract has to have the funds available for the tax so the blockchain can get them.

So, sent some LUNC to the contract to ensure that there are funds available to pay the tax even if the calculations in the contract come up a bit short. So with 1000 LUNC in the contract and 117,224 in my wallet. I'm still getting the error. Please see screenshots. I know its not much, but it's costing me LUNC to keep trying to make this work. Is there some other way to perform this tests/checks so that I don't have to keep paying?
![image](https://user-images.githubusercontent.com/55359362/210488250-84d56cff-0e73-45a2-b32c-ae5cc6004b83.png)
![image](https://user-images.githubusercontent.com/55359362/210488270-f5cd7312-d216-4a9b-887a-3cc9355c4867.png)

**Comment by fragwuerdig** [comment]
@edk208 can @ZuluSpl0it use the rebel-2 testnetwork?

**Comment by ZuluSpl0it** [comment]
I've tried, but errors out: 
![image](https://user-images.githubusercontent.com/55359362/210566502-b2cca36b-6d7e-4c4b-aa49-4cd1f19a87f5.png)
![image](https://user-images.githubusercontent.com/55359362/210566536-6bdb0c85-ebfb-4b21-80b4-e8cb78be789b.png)

**Comment by ZuluSpl0it** [comment]
But on the classic mainnet, the same file is ok:
![image](https://user-images.githubusercontent.com/55359362/210566695-844b9832-ec39-457d-a57e-0598d963ef49.png)

**Comment by StrathCole** [comment]
Terra Station cannot be used with rebel testnet. You have to use terrain or terrad

**Comment by edk208** [comment]
Ahh.. this is a symptom of the chain-id's in station.  I can create a forked station and fix it today or tomorrow

**Comment by StrathCole** [comment]
That probably won't be enough as the extension has to be patched too, to confirm the transactions.

**Comment by ZuluSpl0it** [comment]
@StrathCole or @edk208 could you please upload the wasm file to the rebel-2 testnet. I can test out its functionality later.

https://github.com/ZuluSpl0it/contracts/raw/main/contracts/cw20-bonding/cw20_bonding_tax_stays_on_contract.wasm

**Comment by edk208** [comment]
Please use the following webstation for testnet.  It should work with your wasm contract now.
https://45.79.139.229:3001/

**Comment by ZuluSpl0it** [comment]
@edk208 didn't work. This is what I got:
![image](https://user-images.githubusercontent.com/55359362/210937864-398543cb-1ab8-46a6-aab8-d5a2664de491.png)

What are other contracts doing to mitigate this issue? Surely, I can't be the only one experiencing the fee problem.

**Comment by StrathCole** [comment]
Use terrad to upload and manage contracts.
The default Chrome extension does not work for contracts on testnet for me. I use a manually patched one.

**Comment by fragwuerdig** [comment]
@StrathCole can you elaborate what you need to patch for the chrome extension. Maybe you can share a repo for this patched one?

**Comment by StrathCole** [comment]
It's nothing big. The problem is that it needs the `isClassic` marker for the rebel test net which it has not (as that is only hard-coded for columbus).

It is this line in `src/data/query.ts`:

```
--- a/src/data/query.ts
+++ b/src/data/query.ts
@@ -3,7 +3,7 @@ import { LAZY_LIMIT } from "config/constants"
 
 export const useIsClassic = () => {
   const networkName = useChainID()
-  return networkName === "columbus-5" // TODO
+  return networkName === "columbus-5" || networkName === "rebel-2" // TODO
 }
 
 /* refetch */
```

**Comment by ZaradarBH** [comment]
@fragwuerdig mentioned on our daily stand-up that this issue was done. So I have  closed it. Please re-open if needed.
