### ISSUE TITLE
[BUG] Cross-chain bridging

### ISSUE THREAD

**Issue by 413x45h4w** [classic-terra/classic#37]
**Describe the bug**
When a user tries to transfer LUNC crosschain using one of the only functioning bridges (PortalBridge), the PortalBridge smart contracts unnecessarily require the user to reserve 1.2% of the required funds. This is counter-intuitive (since there's no reason for the user to reserve 1.2% now that the tax has been repealed) and has confiscated hundreds of millions of LUNC from users. Whether the transaction succeeds or fails, a 1.2% tax (+ gas) is assessed on the balance attempting to be transferred.

**To Reproduce**
1. use PortalBridge to bridge LUNC from the native chain to, eg, Eth mainnet (https://www.portalbridge.com/#/transfer) 
2. try to transfer >98.8% of your full balance to Eth mainnet
3. follow the steps to transfer
4. lose 1.2%+gas of whatever you tried to transfer, be a failed txn enjoyooor

**Context & versions**
Not sure

**(if applicable) suggested solution**
Get PortalBridge to update their smart contracts

**Comment by ZaradarBH** [comment]
PortalBridge is a L2 application. I would suggest that you reach out to the people operating the application @ https://discord.com/invite/hJfuptmg6b or read their FAQ @ https://docs.wormhole.com/wormhole/faqs
