### ISSUE TITLE
Whitelist concept for burn-tax

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/classic#42]
**Problem definition**
Ed has talked with Binance and they are looking for us to look at options for whitelisting their wallets.

- [x] Port over the whistlist code from classic-core
- [x] Deploy it to a whitelist-concept branch
- [x] Run unit tests to ensure code works
- [x] Add Binance Whitelists

**Comment by inon-man** [comment]
Where are the linked pull requests or issues?

**Comment by ZaradarBH** [comment]
https://www.binance.com/en/support/announcement/binance-to-make-changes-to-the-burning-of-terra-classic-lunc-trading-fees-4769eab576c4479eaa14adc1eb587226

**Comment by ZaradarBH** [comment]
@inon-man out-of-scope just  means its not part  of the "Q1 deliverables", we should still aim to do them, as long as it doesnt happen at the expense of "in-scope" deadlines :)

**Comment by LuncBurner** [comment]
@ZaradarBH Perhaps I'll see if I can find another description for out-of-scope, such as 'Value-add' or something to that effect.

**Comment by ZaradarBH** [comment]
Not sure that will cause  less confusion. Lets stick with the labels as-is and make sure the documentation for each of them is adequate
